blueprint:
  name: Charging + Time Window Helper
  description: >
    Toggles a helper boolean when one or more devices are charging
    and the current time is between a start time and the next alarm.
    Supports a grace period and charging type filtering.
  domain: automation

  input:
    charging_devices:
      name: Devices to Monitor
      selector:
        entity:
          domain: device_tracker
          multiple: true

    charging_attribute:
      name: Charging Attribute
      default: battery_charging
      selector:
        text: {}

    charging_type_attribute:
      name: Charging Type Attribute
      default: charging_type
      selector:
        text: {}

    charging_type_filter:
      name: Charging Type Filter
      default: any
      selector:
        select:
          options:
            - value: any
              label: Any
            - value: wired
              label: Wired
            - value: wireless
              label: Wireless

    grace_period:
      name: Grace Period (minutes)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes

    start_time:
      name: Start Time
      default: "00:30"
      selector:
        time: {}

    alarm_device:
      name: Device With Next Alarm
      selector:
        entity:
          domain: sensor

    helper_boolean:
      name: Helper Boolean
      selector:
        entity:
          domain: input_boolean

trigger:
  # Time pattern triggers every minute to re-check conditions
  - platform: time_pattern
    minutes: "/1"
  # Trigger when the alarm sensor changes
  - platform: state
    entity_id: !input alarm_device

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set any_charging = false %}
              {% for dev in expand(!input charging_devices) %}
                {% set state = state_attr(dev.entity_id, !input charging_attribute) %}
                {% set state_bool = state in [true, 'true', 'on'] %}
                {% set ctype = state_attr(dev.entity_id, !input charging_type_attribute) %}
                {% if state_bool and (!input charging_type_filter == 'any' or (ctype is not none and ctype|lower == !input charging_type_filter)) %}
                  {% set any_charging = true %}
                {% endif %}
              {% endfor %}

              {% set start_dt = now().replace(hour=!input start_time.split(':')[0]|int, minute=!input start_time.split(':')[1]|int, second=0, microsecond=0) %}
              {% set alarm_val = states(!input alarm_device) %}
              {% set end_dt = alarm_val not in ['', 'unknown', 'unavailable'] and as_datetime(alarm_val) or none %}
              {% if end_dt != none and end_dt < now() %}{% set end_dt = end_dt + timedelta(days=1) %}{% endif %}

              {{ any_charging and end_dt != none and now() >= start_dt and now() <= end_dt }}
        sequence:
          - delay:
              minutes: !input grace_period
          - service: input_boolean.turn_on
            target:
              entity_id: !input helper_boolean
      - default:
          - service: input_boolean.turn_off
            target:
              entity_id: !input helper_boolean

mode: restart
