blueprint:
  name: Presence Light with Dual Manual Overrides (Tuya RD24G01)
  description: >
    Controls light(s) based on Tuya RD24G01 mmWave sensor.
    Implements dual manual overrides (ON/OFF) with duration timers.
    Optional disable sensor stops automation entirely.
    Only triggers between sunset and sunrise with customizable offset.
  domain: automation

  input:
    presence_sensor:
      name: Tuya RD24G01 Presence Sensor
      selector:
        entity:
          domain: sensor

    target_lights:
      name: Lights (multi-select)
      selector:
        entity:
          domain: light
          multiple: true

    off_delay:
      name: Auto-off delay (seconds)
      default: 30
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: seconds

    manual_on_override_flag:
      name: Manual ON Override Boolean Helper
      selector:
        entity:
          domain: input_boolean

    manual_off_override_flag:
      name: Manual OFF Override Boolean Helper
      selector:
        entity:
          domain: input_boolean

    manual_on_minutes:
      name: Manual ON Override Duration (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes

    manual_off_minutes:
      name: Manual OFF Override Duration (minutes)
      default: 10
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: minutes

    disable_sensor:
      name: Optional Disable Sensor
      description: If ON, automation is disabled.
      default: ""
      selector:
        entity:
          domain: binary_sensor

    sunset_offset:
      name: Sunset Offset (minutes)
      default: 0
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes

    sunrise_offset:
      name: Sunrise Offset (minutes)
      default: 0
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes

trigger:
  - platform: state
    entity_id: !input presence_sensor
  - platform: state
    entity_id: !input target_lights

action:
  - variables:
      sensor: !input presence_sensor
      lights: !input target_lights
      off_delay: !input off_delay
      on_flag: !input manual_on_override_flag
      off_flag: !input manual_off_override_flag
      on_minutes: !input manual_on_minutes
      off_minutes: !input manual_off_minutes
      disable_sensor: !input disable_sensor
      active_states: ["motion", "stationary"]

  ###########################################################################
  # 0 — Only run between sunset and sunrise (with offsets)
  ###########################################################################
  - choose:
      - conditions:
          - condition: sun
            after: sunset
            after_offset: "{{ (sunset_offset | int) * 60 }}"
            before: sunrise
            before_offset: "{{ (sunrise_offset | int) * 60 }}"
        sequence:
          - service: homeassistant.log
            data:
              message: "Automation triggered during the correct time window."
    default:
      - stop

  ###########################################################################
  # 1 — Optional disable sensor
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ disable_sensor != "" and is_state(disable_sensor, 'on') }}
        sequence:
          - stop:

  ###########################################################################
  # 2 — Manual ON override
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id in lights
                 and trigger.to_state.state == 'on'
                 and trigger.to_state.context.user_id is not none }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_on_override_flag
          - wait_for_trigger:
              - platform: state
                entity_id: !input presence_sensor
                to: "none"
          - delay:
              minutes: !input manual_on_minutes
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_on_override_flag
          - stop:

  ###########################################################################
  # 3 — Manual OFF override
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id in lights
                 and trigger.to_state.state == 'off'
                 and trigger.to_state.context.user_id is not none }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_off_override_flag
          - wait_for_trigger:
              - platform: state
                entity_id: !input presence_sensor
                to: "none"
          - delay:
              minutes: !input manual_off_minutes
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_off_override_flag
          - stop:

  ###########################################################################
  # 4 — Auto ON (blocked by OFF override)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state(off_flag, 'off')
                 and trigger.entity_id == sensor
                 and trigger.from_state.state == 'none'
                 and trigger.to_state.state in active_states }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_lights

  ###########################################################################
  # 5 — Auto OFF (blocked by ON override)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state(on_flag, 'off')
                 and trigger.entity_id == sensor
                 and trigger.to_state.state == 'none'
                 and states(sensor) not in active_states }}
        sequence:
          - delay:
              seconds: !input off_delay
          - condition: state
            entity_id: !input presence_sensor
            state: "none"
          - service: light.turn_off
            target:
              entity_id: !input target_lights

mode: queued
max: 20
