blueprint:
  name: Presence Light with Dual Manual Overrides (Tuya RD24G01) - DEBUG
  description: >
    Controls light(s) based on Tuya RD24G01 mmWave sensor.
    Implements dual manual overrides (ON/OFF) with duration timers.
    Optional disable sensor stops automation entirely.
    Only triggers between sunset and sunrise with customizable offset.
    This version includes extensive logging for debugging.
  domain: automation

  input:
    presence_sensor:
      name: Tuya RD24G01 Presence Sensor
      selector:
        entity:
          domain: sensor

    target_lights:
      name: Lights (multi-select)
      selector:
        entity:
          domain: light
          multiple: true

    off_delay:
      name: Auto-off delay (seconds)
      default: 30
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: seconds

    manual_on_override_flag:
      name: Manual ON Override Boolean Helper
      selector:
        entity:
          domain: input_boolean

    manual_off_override_flag:
      name: Manual OFF Override Boolean Helper
      selector:
        entity:
          domain: input_boolean

    manual_on_minutes:
      name: Manual ON Override Duration (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes

    manual_off_minutes:
      name: Manual OFF Override Duration (minutes)
      default: 10
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: minutes

    disable_sensor:
      name: Optional Disable Sensor
      description: If ON, automation is disabled.
      default: ""
      selector:
        entity:
          domain: binary_sensor

    sunset_offset:
      name: Sunset Offset (minutes)
      default: 0
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes

    sunrise_offset:
      name: Sunrise Offset (minutes)
      default: 0
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes

# The trigger for the automation
trigger:
  - platform: state
    entity_id: !input presence_sensor
  - platform: state
    entity_id: !input target_lights

# The action sequence
action:
  # Define variables for easy access
  - variables:
      sensor: !input presence_sensor
      lights: !input target_lights
      off_delay: !input off_delay
      on_flag: !input manual_on_override_flag
      off_flag: !input manual_off_override_flag
      on_minutes: !input manual_on_minutes
      off_minutes: !input manual_off_minutes
      disable_sensor: !input disable_sensor
      sunset_offset: !input sunset_offset
      sunrise_offset: !input sunrise_offset
      active_states: ["motion", "stationary"]

  # Initial log entry
  - service: system_log.write
    data:
      message: "Presence Light [{{ sensor }}]: Triggered by {{ trigger.entity_id }} from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}."
      level: info

  ###########################################################################
  # 0 — Only run between sunset and sunrise (with offsets)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {%- set sunset_offset_sec = (sunset_offset | int(0)) * 60 %}
              {%- set sunrise_offset_sec = (sunrise_offset | int(0)) * 60 %}
              {%- set start_time_obj = sunrise() + timedelta(seconds=sunrise_offset_sec) %}
              {%- set end_time_obj = sunset() + timedelta(seconds=sunset_offset_sec) %}
              {%- set now_obj = now() %}
              {%- if start_time_obj < end_time_obj %}
                {{ now_obj > end_time_obj or now_obj < start_time_obj }}
              {%- else %}
                {{ now_obj > end_time_obj and now_obj < start_time_obj }}
              {%- endif %}
        sequence:
          - service: system_log.write
            data:
              message: "Presence Light [{{ sensor }}]: [OK] Passed time window check."
              level: info
    default:
      - service: system_log.write
        data:
          message: "Presence Light [{{ sensor }}]: [FAIL] Stopped. Outside time window."
          level: warning
      - stop:

  ###########################################################################
  # 1 — Optional disable sensor
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ disable_sensor != "" and is_state(disable_sensor, 'on') }}
        sequence:
          - service: system_log.write
            data:
              message: "Presence Light [{{ sensor }}]: [FAIL] Stopped. Disable sensor '{{ disable_sensor }}' is ON."
              level: warning
          - stop:
  - service: system_log.write
    data:
      message: "Presence Light [{{ sensor }}]: [OK] Passed disable sensor check."
      level: info

  ###########################################################################
  # 2 — Manual ON override
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id in lights
                 and trigger.to_state.state == 'on'
                 and trigger.to_state.context.user_id is not none }}
        sequence:
          - service: system_log.write
            data:
              message: "Presence Light [{{ sensor }}]: [INFO] Manual ON override triggered. Activating flag and stopping automation."
              level: info
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_on_override_flag
          - wait_for_trigger:
              - platform: template
                value_template: "{{ is_state(sensor, 'none') }}"
          - delay:
              minutes: !input manual_on_minutes
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_on_override_flag
          - stop:

  ###########################################################################
  # 3 — Manual OFF override
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id in lights
                 and trigger.to_state.state == 'off'
                 and trigger.to_state.context.user_id is not none }}
        sequence:
          - service: system_log.write
            data:
              message: "Presence Light [{{ sensor }}]: [INFO] Manual OFF override triggered. Activating flag and stopping automation."
              level: info
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_off_override_flag
          - wait_for_trigger:
              - platform: template
                value_template: "{{ is_state(sensor, 'none') }}"
          - delay:
              minutes: !input manual_off_minutes
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_off_override_flag
          - stop:
  - service: system_log.write
    data:
      message: "Presence Light [{{ sensor }}]: [OK] Passed manual override checks."
      level: info

  ###########################################################################
  # 4 — Auto ON (blocked by OFF override)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state(off_flag, 'off')
                 and trigger.entity_id == sensor
                 and trigger.from_state.state == 'none'
                 and trigger.to_state.state in active_states }}
        sequence:
          - service: system_log.write
            data:
              message: "Presence Light [{{ sensor }}]: [OK] Auto-ON condition met. Turning lights on."
              level: info
          - service: light.turn_on
            target:
              entity_id: !input target_lights
    default:
      - service: system_log.write
        data:
          message: "Presence Light [{{ sensor }}]: [FAIL] Auto-ON condition NOT met. Details: OFF_Flag_is_off={{ is_state(off_flag, 'off') }}, Trigger_is_sensor={{ trigger.entity_id == sensor }}, FromState_was_none={{ trigger.from_state.state == 'none' }}, ToState_is_active={{ trigger.to_state.state in active_states }}"
          level: warning

  ###########################################################################
  # 5 — Auto OFF (blocked by ON override)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state(on_flag, 'off')
                 and trigger.entity_id == sensor
                 and trigger.to_state.state == 'none'
                 and states(sensor) not in active_states }}
        sequence:
          - service: system_log.write
            data:
              message: "Presence Light [{{ sensor }}]: [OK] Auto-OFF condition met. Starting delay."
              level: info
          - delay:
              seconds: !input off_delay
          - condition: template
            value_template: "{{ is_state(sensor, 'none') }}"
          - service: system_log.write
            data:
              message: "Presence Light [{{ sensor }}]: [OK] Delay finished. Sensor still 'none'. Turning lights off."
              level: info
          - service: light.turn_off
            target:
              entity_id: !input target_lights
    default:
      - service: system_log.write
        data:
          message: "Presence Light [{{ sensor }}]: [FAIL] Auto-OFF condition NOT met."
          level: warning

mode: queued
max: 20
